### PR TITLE
[WIP] Add a Semigroup instance

### PR DESCRIPTION
**Pull request by k-bx**

### CODE REVIEW

**Comment by nikita-volkov** [comment]
The tests are failing for some reason. Any idea?

**Comment by k-bx** [comment]
Very interesting! I confirm they start failing locally on 8.2.2, not clear to me why, yet.

**Comment by nikita-volkov** [comment]
The tests are still failing (

**Comment by k-bx** [comment]
Yes, if you don’t mind I’d keep it open with a WIP label until someone has time to take a closer look. Thank you.

**Comment by nikita-volkov** [comment]
Found the issue. It was due to a loop in the def of `(<>)` that the way you've imported things introduced. It's fixed now and the new version is released.

**Pull request merged**
